/*
 * ExploreContent.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

/**
 *
 * @author  __USER__
 */
public class ExplorePanel extends javax.swing.JPanel {

	/** Creates new form ExploreContent */
	public ExplorePanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel151 = new javax.swing.JLabel();
		jLabel153 = new javax.swing.JLabel();
		jLabel154 = new javax.swing.JLabel();
		jLabel150 = new javax.swing.JLabel();

		jPanel1.setLayout(null);

		jLabel151.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel151.setText("\u5a92\u4f53\u540d\u79f0");
		jPanel1.add(jLabel151);
		jLabel151.setBounds(10, 10, 56, 20);

		jLabel153.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel153.setText("\u00b7");
		jPanel1.add(jLabel153);
		jLabel153.setBounds(70, 10, 10, 20);

		jLabel154.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel154.setText("\u65f6\u95f4");
		jPanel1.add(jLabel154);
		jLabel154.setBounds(80, 10, 28, 20);

		jLabel150.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36));
		jLabel150.setText("\u5c01\u9762");
		jPanel1.add(jLabel150);
		jLabel150.setBounds(610, 0, 190, 170);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel150;
	private javax.swing.JLabel jLabel151;
	private javax.swing.JLabel jLabel153;
	private javax.swing.JLabel jLabel154;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}