/*
 * ListPanel_1.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

/**
 *
 * @author  __USER__
 */
public class ListPanel_1 extends javax.swing.JPanel {

	/** Creates new form ListPanel_1 */
	public ListPanel_1() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();

		jPanel1.setLayout(null);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("\u5c01\u9762");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(650, 0, 150, 150);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setText("\u6635\u79f0");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(10, 10, 130, 19);

		jLabel3.setForeground(new java.awt.Color(153, 153, 153));
		jLabel3.setText("\u7528\u6237\u540d");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(150, 10, 170, 15);

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel4.setText("\u6807\u9898");
		jPanel1.add(jLabel4);
		jLabel4.setBounds(10, 40, 610, 20);

		jLabel5.setText("\u63cf\u8ff0");
		jPanel1.add(jLabel5);
		jLabel5.setBounds(10, 70, 620, 50);

		jLabel6.setText("\u6570\u5b57");
		jPanel1.add(jLabel6);
		jLabel6.setBounds(10, 130, 50, 15);

		jLabel7.setText("\u6210\u5458\u00b7");
		jPanel1.add(jLabel7);
		jLabel7.setBounds(70, 130, 36, 15);

		jLabel8.setText("\u6570\u5b57");
		jPanel1.add(jLabel8);
		jLabel8.setBounds(120, 130, 24, 15);

		jLabel9.setText("\u8ba2\u9605\u8005");
		jPanel1.add(jLabel9);
		jLabel9.setBounds(170, 130, 36, 15);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
				javax.swing.GroupLayout.PREFERRED_SIZE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}