/*
 * ListPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

/**
 *
 * @author  __USER__
 */
public class ListPanel extends javax.swing.JPanel {

	/** Creates new form ListPanel */
	public ListPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		jPanel1.setLayout(null);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("\u5934\u50cf");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 100, 100);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setText("\u6635\u79f0");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(110, 10, 150, 19);

		jLabel3.setForeground(new java.awt.Color(153, 153, 153));
		jLabel3.setText("\u7528\u6237\u540d");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(270, 10, 180, 17);

		jLabel4.setText("\u4e2a\u6027\u7b7e\u540d");
		jPanel1.add(jLabel4);
		jLabel4.setBounds(110, 40, 510, 60);

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton1.setForeground(new java.awt.Color(0, 102, 255));
		jButton1.setText("\u5173\u6ce8");
		jPanel1.add(jButton1);
		jButton1.setBounds(680, 30, 81, 30);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
				javax.swing.GroupLayout.PREFERRED_SIZE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}