/*
 * MomentView.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

/**
 *
 * @author  __USER__
 */
public class MomentPanel extends javax.swing.JPanel {

	/** Creates new form MomentView */
	public MomentPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		jPanel1.setLayout(null);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("\u5c01\u9762");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(650, 0, 150, 150);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setText("\u77ac\u95f4\u6807\u9898");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(10, 10, 580, 40);

		jLabel3.setText("\u77ac\u95f4\u63cf\u8ff0");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(10, 60, 610, 50);

		jLabel4.setText("\u6dfb\u52a0\u4e8e");
		jPanel1.add(jLabel4);
		jLabel4.setBounds(10, 120, 36, 17);

		jLabel5.setText("\u65f6\u95f4");
		jPanel1.add(jLabel5);
		jLabel5.setBounds(60, 120, 60, 17);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
				javax.swing.GroupLayout.PREFERRED_SIZE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}