/*
 * RecomFollowPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.io.IOException;
import java.net.UnknownHostException;
import java.sql.SQLException;

import javax.swing.ImageIcon;

import org.omg.CORBA.CTX_RESTRICT_SCOPE;

import server.TClient;

import model.User;

/**
 *
 * @author  __USER__
 */
public class RecomFollowPanel extends javax.swing.JPanel {
	User u;
	User user;

	/** Creates new form RecomFollowPanel */
	public RecomFollowPanel(User u, User user) {
		initComponents();
		if (user.getPicfname() != null) {
			ImageIcon img = new ImageIcon("C:Twitter/CLIB/picture/"
					+ user.getPicfname());
			img.setImage(img.getImage().getScaledInstance(jLabel1.getWidth(),
					jLabel1.getHeight(), Image.SCALE_DEFAULT));
			jLabel1.setIcon(img);
		}
		jLabel2.setText(user.getName());
		jLabel3.setText(user.getId());
		if (u.getId().equals(user.getId())) {
			jButton1.setVisible(false);
		} else if (user.isFollowed()) {
			jButton1.setText("取消关注");
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		jPanel1.setLayout(null);

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("\u5934\u50cf");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(10, 10, 100, 100);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setText("\u6635\u79f0");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(130, 10, 150, 19);

		jLabel3.setForeground(new java.awt.Color(153, 153, 153));
		jLabel3.setText("\u7528\u6237\u540d");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(130, 40, 130, 20);

		jButton1.setForeground(new java.awt.Color(0, 153, 255));
		jButton1.setText("\u5173\u6ce8");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1);
		jButton1.setBounds(650, 10, 110, 40);

		jScrollPane1
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane1
				.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

		jTextArea1.setColumns(20);
		jTextArea1.setEditable(false);
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1.setWrapStyleWord(true);
		jScrollPane1.setViewportView(jTextArea1);

		jPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(130, 70, 630, 90);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 781,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			TClient.follow(u, user.getId(), user.isFollowed());
			if (user.isFollowed()) {
				jButton1.setText("关注");
				user.setFollowed(false);
			} else {
				jButton1.setText("取消关注");
				user.setFollowed(true);
			}
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}