/*
 * RegisterView.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.io.IOException;

import javax.swing.JOptionPane;

import server.TClient;

/**
 *
 * @author  __USER__
 */
public class RegisterView extends javax.swing.JFrame {

	/** Creates new form RegisterView */
	public RegisterView() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jPasswordField2 = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(96, 168, 220));
		jPanel1.setForeground(new java.awt.Color(255, 255, 255));
		jPanel1.setLayout(null);
		jPanel1.add(jTextField1);
		jTextField1.setBounds(80, 320, 350, 40);
		jPanel1.add(jPasswordField1);
		jPasswordField1.setBounds(80, 460, 350, 40);

		jLabel1.setBackground(new java.awt.Color(255, 255, 255));
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/LOGO.png"))); // NOI18N
		jLabel1.setText("jLabel1");
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 500, 300);

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton1.setForeground(new java.awt.Color(0, 153, 255));
		jButton1.setText("\u6ce8\u518c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1);
		jButton1.setBounds(210, 520, 90, 40);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2
				.setText("\u5df2\u6709\u8d26\u53f7\uff1f\u73b0\u5728\u53bb\u767b\u5f55");
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel2MouseClicked(evt);
			}
		});
		jPanel1.add(jLabel2);
		jLabel2.setBounds(180, 570, 150, 19);
		jPanel1.add(jPasswordField2);
		jPasswordField2.setBounds(80, 390, 350, 40);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String name=jTextField1.getText();
		String password1=jPasswordField1.getText();
		String password2=jPasswordField2.getText();
		if(!password1.equals(password2)){
			JOptionPane.showMessageDialog(this,"两次密码不一致");
		}else{
			try {
				TClient.register(name, password1);
				JOptionPane.showMessageDialog(this,"注册成功");
				new LoginView().setVisible(true);
				this.dispose();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {
		new LoginView().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			//TODO exception
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegisterView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}