/*
 * SentTweetView.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import model.User;

import server.TClient;

/**
 *
 * @author  __USER__
 */
public class SentTweetView extends javax.swing.JFrame {
	private MainView mv;
	private User u;
	private int mediaType = 0;
	private int mediaCount = 0;
	private ArrayList<File> media = new ArrayList<File>();
	private ArrayList<String> fe = new ArrayList<String>();

	/** Creates new form SentTweetView */
	public SentTweetView(MainView mv, User u) {
		initComponents();
		this.setLocationRelativeTo(null);
		this.mv = mv;
		this.u = u;
		setImg(u.getPicfname(),jLabel2);
	}
	public void setImg(String picfname, JLabel jlb) {
		ImageIcon img = new ImageIcon("C:Twitter/CLIB/picture/" + picfname);
		img.setImage(img.getImage().getScaledInstance(jlb.getWidth(),
				jlb.getHeight(), Image.SCALE_DEFAULT));
		jlb.setIcon(img);
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton3 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setLayout(null);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(90, 20, 660, 190);

		jButton3.setForeground(new java.awt.Color(0, 153, 255));
		jButton3.setText("\u53d1\u9001\u63a8\u6587");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton3);
		jButton3.setBounds(650, 230, 93, 29);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/插入图片.png"))); // NOI18N
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel1MouseClicked(evt);
			}
		});
		jPanel1.add(jLabel1);
		jLabel1.setBounds(100, 230, 40, 25);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/资料.png"))); // NOI18N
		jPanel1.add(jLabel2);
		jLabel2.setBounds(20, 10, 50, 50);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 785,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 269,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
		if (mediaCount < 4) {
			JFileChooser jfc = new JFileChooser();
			jfc.showOpenDialog(this);
			File f = jfc.getSelectedFile();
			if (f == null || !f.exists()) {
				JOptionPane.showMessageDialog(this, "请选择文件");
				return;
			}
			media.add(f);
			fe.add(f.getName().substring(f.getName().lastIndexOf(".") + 1));
			jLabel1.setText(++mediaCount + "");
			mediaType=2;
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		String cont = jTextArea1.getText();
		if (cont.equals("")) {
			JOptionPane.showMessageDialog(this, "内容不能为空！！！");
		} else {
			try {
				TClient.tweet(u, cont, mediaType, media, fe);
				mv.getMainTw();
				this.dispose();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (ClassNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();
		} catch (Exception e) {
			//TODO exception
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SentTweetView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables

}